# Generated by Django 3.2.7 on 2023-01-13 18:04

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.question_file_name),
        ),
    ]
