# Generated by Django 3.2.7 on 2023-01-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_question',
            field=models.BooleanField(default=False),
        ),
    ]
